// dto/LandDTO.js

class LandDTO {
    constructor(id, name, address, lga, state, country, sqm, isSold, freshLand, start, end,created_by_name,type) {
      this.id = id;
      this.name = name;
      this.address = address;
      this.lga = lga;
      this.state = state;
      this.country = country;
      this.sqm = sqm;
      this.isSold = isSold;
      this.freshLand = freshLand;
      this.start = start;
      this.end = end;
      this.created_by_name = created_by_name;
      this.type = type;

    }
  
    // Static method to create DTO from Land model instance
    static fromModel(landModel) {
      return new LandDTO(
        landModel.id,
        landModel.name,
        landModel.address,
        landModel.lga,
        landModel.state,
        landModel.country,
        landModel.sqm,
        landModel.isSold,
        landModel.freshLand,
        landModel.start,
        landModel.end,
        landModel.created_by_name,
        landModel.type,
      );
    }
  
    // Static method to validate incoming data for Land creation
    static validateCreateData(data) {
      if (!data.name || !data.address || !data.sqm) {
        throw new Error('Required fields: name, address, sqm');
      }
  
      return new LandDTO(
        null, // ID is generated by the DB
        data.name,
        data.address,
        data.lga || null,
        data.state || null,
        data.country || null,
        data.sqm,
        data.isSold || false,
        data.freshLand || true,
        data.start || null,
        data.end || null,
        data.created_by_name || null,
        data.type || null
      );
    }
  
    // Static method to validate data for Land update
    static validateUpdateData(data) {
      if (!data.name && !data.address && !data.sqm) {
        throw new Error('At least one of name, address, or sqm should be provided for update');
      }
  
      return new LandDTO(
        data.id, // Use the existing ID for updates
        data.name || null,
        data.address || null,
        data.lga || null,
        data.state || null,
        data.country || null,
        data.sqm || null,
        data.isSold || null,
        data.freshLand || null,
        data.start || null,
        data.end || null,
        data.created_by_name || null,
        data.type || null
      );
    }
  }
  
  module.exports = LandDTO;
  